"""
Curated Recommendation Corpus (100+ entries)
=============================================

Static data module — populates the Recommendation Knowledge Base.

* No kg CO2e numbers anywhere — only activity keys, text, and metadata.
* Category and Difficulty enums are imported from recommendation_engine.py.
* The existing 10 RULE_LIBRARY ideas are reused/expanded as a starting subset
  with a NEW id scheme.
"""

from __future__ import annotations

from knowledge_base import RecommendationDefinition
from recommendation_engine import Category, Difficulty

# ----------------------------------------------------------------------------
# Food — 18 entries
# ----------------------------------------------------------------------------

_FOOD: list[RecommendationDefinition] = [
    RecommendationDefinition(
        id="FOO-001",
        category=Category.FOOD,
        title="Skip Chicken Today",
        description_template="Replace today's chicken meal with paneer for a lower-carbon protein option.",
        action_type="chicken_to_paneer",
        baseline_activity_key="chicken_curry_cooked",
        recommended_activity_key="paneer_curry_cooked",
        default_quantity=0.35,
        unit="kg",
        difficulty=Difficulty.EASY,
        tags=("protein_swap", "vegetarian", "indian_cuisine"),
        applicable_pattern_types=("meal_day_of_week",),
        cold_start_eligible=False,
        requires_mature=False,
        estimated_impact_band="medium",
        conditions={"min_pattern_confidence": 0.35},
        source_note="DEFRA food swap category — poultry to dairy protein",
    ),
    RecommendationDefinition(
        id="FOO-002",
        category=Category.FOOD,
        title="Try Lentils Instead",
        description_template="Replace today's chicken meal with a lentil dish for a plant-based protein source.",
        action_type="chicken_to_lentils",
        baseline_activity_key="chicken_curry_cooked",
        recommended_activity_key="lentil_curry_cooked",
        default_quantity=0.35,
        unit="kg",
        difficulty=Difficulty.EASY,
        tags=("protein_swap", "vegan", "plant_based", "indian_cuisine"),
        applicable_pattern_types=("meal_day_of_week",),
        cold_start_eligible=False,
        requires_mature=False,
        estimated_impact_band="medium",
        conditions={"min_pattern_confidence": 0.35},
        source_note="DEFRA food swap category — poultry to legumes",
    ),
    RecommendationDefinition(
        id="FOO-003",
        category=Category.FOOD,
        title="Swap Beef for Black Beans",
        description_template="Replace {count} serving of beef with black beans in your next meal.",
        action_type="beef_to_beans",
        baseline_activity_key="beef_stew_cooked",
        recommended_activity_key="black_bean_stew_cooked",
        default_quantity=0.25,
        unit="kg",
        difficulty=Difficulty.EASY,
        tags=("protein_swap", "vegan", "legumes", "red_meat_reduction"),
        applicable_pattern_types=("meal_day_of_week", "meal_type"),
        cold_start_eligible=False,
        requires_mature=False,
        estimated_impact_band="high",
        conditions={},
        source_note="Poore & Nemecek 2018 — red meat to legumes",
    ),
    RecommendationDefinition(
        id="FOO-004",
        category=Category.FOOD,
        title="Try Tofu Instead of Beef",
        description_template="Use tofu as a beef replacement in your next stir-fry or curry.",
        action_type="beef_to_tofu",
        baseline_activity_key="beef_stir_fry_cooked",
        recommended_activity_key="tofu_stir_fry_cooked",
        default_quantity=0.25,
        unit="kg",
        difficulty=Difficulty.MODERATE,
        tags=("protein_swap", "vegetarian", "soy", "asian_cuisine"),
        applicable_pattern_types=("meal_day_of_week", "meal_type"),
        cold_start_eligible=False,
        requires_mature=False,
        estimated_impact_band="high",
        conditions={},
        source_note="Poore & Nemecek 2018 — red meat to soy protein",
    ),
    RecommendationDefinition(
        id="FOO-005",
        category=Category.FOOD,
        title="Choose Chickpeas Over Lamb",
        description_template="Replace lamb with chickpeas in your next curry or stew.",
        action_type="lamb_to_chickpeas",
        baseline_activity_key="lamb_curry_cooked",
        recommended_activity_key="chickpea_curry_cooked",
        default_quantity=0.30,
        unit="kg",
        difficulty=Difficulty.EASY,
        tags=("protein_swap", "vegan", "legumes", "mediterranean"),
        applicable_pattern_types=("meal_day_of_week",),
        cold_start_eligible=False,
        requires_mature=False,
        estimated_impact_band="high",
        conditions={},
        source_note="DEFRA food swap category — ruminant meat to legumes",
    ),
    RecommendationDefinition(
        id="FOO-006",
        category=Category.FOOD,
        title="Swap Pork for Tempeh",
        description_template="Use tempeh as a pork alternative in your next meal.",
        action_type="pork_to_tempeh",
        baseline_activity_key="pork_stir_fry_cooked",
        recommended_activity_key="tempeh_stir_fry_cooked",
        default_quantity=0.25,
        unit="kg",
        difficulty=Difficulty.MODERATE,
        tags=("protein_swap", "vegetarian", "fermented", "asian_cuisine"),
        applicable_pattern_types=("meal_day_of_week", "meal_type"),
        cold_start_eligible=False,
        requires_mature=False,
        estimated_impact_band="medium",
        conditions={},
        source_note="DEFRA food swap category — pork to soy protein",
    ),
    RecommendationDefinition(
        id="FOO-007",
        category=Category.FOOD,
        title="Replace Fish with Lentils",
        description_template="Try a lentil dish instead of fish for your next protein serving.",
        action_type="fish_to_lentils",
        baseline_activity_key="grilled_fish_cooked",
        recommended_activity_key="lentil_dal_cooked",
        default_quantity=0.30,
        unit="kg",
        difficulty=Difficulty.EASY,
        tags=("protein_swap", "vegan", "legumes"),
        applicable_pattern_types=("meal_day_of_week",),
        cold_start_eligible=False,
        requires_mature=False,
        estimated_impact_band="medium",
        conditions={},
        source_note="DEFRA food swap category — seafood to legumes",
    ),
    RecommendationDefinition(
        id="FOO-008",
        category=Category.FOOD,
        title="Switch to Oat Milk",
        description_template="Use oat milk instead of dairy milk in your coffee or cereal.",
        action_type="dairy_milk_to_oat",
        baseline_activity_key="cow_milk_consumed",
        recommended_activity_key="oat_milk_consumed",
        default_quantity=0.25,
        unit="litre",
        difficulty=Difficulty.EASY,
        tags=("dairy_alternative", "vegan", "breakfast"),
        applicable_pattern_types=("beverage_habit",),
        cold_start_eligible=True,
        requires_mature=False,
        estimated_impact_band="low",
        conditions={},
        source_note="Oxford University food climate research — dairy to oat milk",
    ),
    RecommendationDefinition(
        id="FOO-009",
        category=Category.FOOD,
        title="Try Soy Milk Instead",
        description_template="Swap dairy milk for soy milk in your next drink or recipe.",
        action_type="dairy_milk_to_soy",
        baseline_activity_key="cow_milk_consumed",
        recommended_activity_key="soy_milk_consumed",
        default_quantity=0.25,
        unit="litre",
        difficulty=Difficulty.EASY,
        tags=("dairy_alternative", "vegan", "breakfast"),
        applicable_pattern_types=("beverage_habit",),
        cold_start_eligible=True,
        requires_mature=False,
        estimated_impact_band="low",
        conditions={},
        source_note="Oxford University food climate research — dairy to soy milk",
    ),
    RecommendationDefinition(
        id="FOO-010",
        category=Category.FOOD,
        title="Use Nutritional Yeast Instead of Cheese",
        description_template="Sprinkle nutritional yeast on your pasta or popcorn instead of grated cheese.",
        action_type="cheese_to_nutritional_yeast",
        baseline_activity_key="grated_cheese_used",
        recommended_activity_key="nutritional_yeast_used",
        default_quantity=0.03,
        unit="kg",
        difficulty=Difficulty.EASY,
        tags=("dairy_alternative", "vegan", "umami"),
        applicable_pattern_types=("meal_type",),
        cold_start_eligible=True,
        requires_mature=False,
        estimated_impact_band="low",
        conditions={},
        source_note="General plant-based cooking substitution",
    ),
    RecommendationDefinition(
        id="FOO-011",
        category=Category.FOOD,
        title="Switch to Coconut Yogurt",
        description_template="Try coconut yogurt instead of dairy yogurt for breakfast or a snack.",
        action_type="yogurt_to_coconut",
        baseline_activity_key="dairy_yogurt_consumed",
        recommended_activity_key="coconut_yogurt_consumed",
        default_quantity=0.15,
        unit="kg",
        difficulty=Difficulty.EASY,
        tags=("dairy_alternative", "vegan", "breakfast", "snack"),
        applicable_pattern_types=("beverage_habit", "meal_type"),
        cold_start_eligible=True,
        requires_mature=False,
        estimated_impact_band="low",
        conditions={},
        source_note="General plant-based dairy alternatives",
    ),
    RecommendationDefinition(
        id="FOO-012",
        category=Category.FOOD,
        title="Try a Chickpea Scramble",
        description_template="Make a chickpea flour scramble instead of scrambled eggs for breakfast.",
        action_type="eggs_to_chickpea_scramble",
        baseline_activity_key="scrambled_eggs_cooked",
        recommended_activity_key="chickpea_scramble_cooked",
        default_quantity=2.0,
        unit="egg_equivalent",
        difficulty=Difficulty.MODERATE,
        tags=("protein_swap", "vegan", "breakfast"),
        applicable_pattern_types=("meal_day_of_week",),
        cold_start_eligible=False,
        requires_mature=False,
        estimated_impact_band="medium",
        conditions={},
        source_note="General plant-based egg substitution",
    ),
    RecommendationDefinition(
        id="FOO-013",
        category=Category.FOOD,
        title="Choose White Meat Over Red",
        description_template="Opt for chicken or turkey instead of beef or lamb in your next meal.",
        action_type="red_meat_to_white_meat",
        baseline_activity_key="beef_or_lamb_cooked",
        recommended_activity_key="chicken_cooked",
        default_quantity=0.30,
        unit="kg",
        difficulty=Difficulty.EASY,
        tags=("meat_reduction", "lower_carbon_meat"),
        applicable_pattern_types=("meal_day_of_week", "meal_type"),
        cold_start_eligible=False,
        requires_mature=False,
        estimated_impact_band="medium",
        conditions={},
        source_note="Poore & Nemecek 2018 — ruminant to monogastric meat",
    ),
    RecommendationDefinition(
        id="FOO-014",
        category=Category.FOOD,
        title="Swap Processed Meat for Legumes",
        description_template="Replace sausages or bacon with lentils or beans at your next meal.",
        action_type="processed_meat_to_legumes",
        baseline_activity_key="processed_meat_cooked",
        recommended_activity_key="mixed_legumes_cooked",
        default_quantity=0.25,
        unit="kg",
        difficulty=Difficulty.EASY,
        tags=("protein_swap", "vegan", "processed_food_reduction"),
        applicable_pattern_types=("meal_day_of_week",),
        cold_start_eligible=False,
        requires_mature=False,
        estimated_impact_band="medium",
        conditions={},
        source_note="DEFRA food swap category — processed meat to legumes",
    ),
    RecommendationDefinition(
        id="FOO-015",
        category=Category.FOOD,
        title="Cook with Olive Oil Instead of Butter",
        description_template="Use olive oil in place of butter for sautéing or baking.",
        action_type="butter_to_olive_oil",
        baseline_activity_key="butter_used",
        recommended_activity_key="olive_oil_used",
        default_quantity=0.02,
        unit="kg",
        difficulty=Difficulty.EASY,
        tags=("fat_swap", "vegetarian", "mediterranean"),
        applicable_pattern_types=("cooking_habit",),
        cold_start_eligible=True,
        requires_mature=False,
        estimated_impact_band="low",
        conditions={},
        source_note="General cooking substitution — dairy fat to plant oil",
    ),
    RecommendationDefinition(
        id="FOO-016",
        category=Category.FOOD,
        title="Buy Local and Seasonal Produce",
        description_template="Choose locally grown, in-season vegetables instead of imported out-of-season options.",
        action_type="imported_veg_to_local_seasonal",
        baseline_activity_key="imported_out_of_season_veg",
        recommended_activity_key="local_seasonal_veg",
        default_quantity=0.50,
        unit="kg",
        difficulty=Difficulty.EASY,
        tags=("local_food", "seasonal", "food_miles"),
        applicable_pattern_types=("shopping_habit",),
        cold_start_eligible=True,
        requires_mature=False,
        estimated_impact_band="low",
        conditions={},
        source_note="DEFRA food miles guidance",
    ),
    RecommendationDefinition(
        id="FOO-017",
        category=Category.FOOD,
        title="Plan Your Meals to Reduce Waste",
        description_template="Plan meals for the week to cut down on food that gets thrown away.",
        action_type="high_food_waste_to_meal_plan",
        baseline_activity_key="unplanned_food_purchase",
        recommended_activity_key="meal_planned_purchase",
        default_quantity=1.0,
        unit="week",
        difficulty=Difficulty.MODERATE,
        tags=("food_waste", "planning", "zero_waste"),
        applicable_pattern_types=("waste_pattern",),
        cold_start_eligible=True,
        requires_mature=False,
        estimated_impact_band="medium",
        conditions={},
        source_note="WRAP food waste reduction guidance",
    ),
    RecommendationDefinition(
        id="FOO-018",
        category=Category.FOOD,
        title="Drink Tap Water Instead of Bottled",
        description_template="Fill a reusable bottle from the tap instead of buying bottled water with your meal.",
        action_type="bottled_water_to_tap",
        baseline_activity_key="bottled_water_consumed",
        recommended_activity_key="tap_water_consumed",
        default_quantity=0.50,
        unit="litre",
        difficulty=Difficulty.EASY,
        tags=("water", "plastic_reduction", "zero_waste"),
        applicable_pattern_types=("beverage_habit",),
        cold_start_eligible=True,
        requires_mature=False,
        estimated_impact_band="low",
        conditions={},
        source_note="General plastic and transport reduction",
    ),
]

# ----------------------------------------------------------------------------
# Transport — 18 entries
# ----------------------------------------------------------------------------

_TRANSPORT: list[RecommendationDefinition] = [
    RecommendationDefinition(
        id="TRN-001",
        category=Category.TRANSPORT,
        title="Carpool to Work",
        description_template="Share today's commute instead of driving solo.",
        action_type="solo_car_to_carpool",
        baseline_activity_key="car_solo_commute",
        recommended_activity_key="car_carpool_commute",
        default_quantity=6.0,
        unit="km",
        difficulty=Difficulty.MODERATE,
        tags=("commute", "shared_mobility", "road"),
        applicable_pattern_types=("transport_weekday",),
        cold_start_eligible=False,
        requires_mature=False,
        estimated_impact_band="medium",
        conditions={},
        source_note="DEFRA transport swap category — single occupancy to carpool",
    ),
    RecommendationDefinition(
        id="TRN-002",
        category=Category.TRANSPORT,
        title="Try Public Transport",
        description_template="Use a bus or metro instead of driving for a short trip.",
        action_type="solo_car_to_public_transit",
        baseline_activity_key="car_solo_commute",
        recommended_activity_key="bus_commute",
        default_quantity=6.0,
        unit="km",
        difficulty=Difficulty.EASY,
        tags=("commute", "public_transit", "road"),
        applicable_pattern_types=("transport_weekday",),
        cold_start_eligible=True,
        requires_mature=False,
        estimated_impact_band="medium",
        conditions={},
        source_note="DEFRA transport swap category — car to bus",
    ),
    RecommendationDefinition(
        id="TRN-003",
        category=Category.TRANSPORT,
        title="Take the Metro Instead",
        description_template="Use the metro instead of driving for today's trip.",
        action_type="solo_car_to_metro",
        baseline_activity_key="car_solo_commute",
        recommended_activity_key="metro_commute",
        default_quantity=6.0,
        unit="km",
        difficulty=Difficulty.EASY,
        tags=("commute", "public_transit", "rail"),
        applicable_pattern_types=("transport_weekday",),
        cold_start_eligible=False,
        requires_mature=False,
        estimated_impact_band="medium",
        conditions={},
        source_note="DEFRA transport swap category — car to metro/rail",
    ),
    RecommendationDefinition(
        id="TRN-004",
        category=Category.TRANSPORT,
        title="Swap the Two-Wheeler for the Bus",
        description_template="Use public transport instead of your two-wheeler today.",
        action_type="two_wheeler_to_public_transit",
        baseline_activity_key="two_wheeler_solo_commute",
        recommended_activity_key="bus_commute",
        default_quantity=6.0,
        unit="km",
        difficulty=Difficulty.EASY,
        tags=("commute", "public_transit", "two_wheeler"),
        applicable_pattern_types=("transport_weekday",),
        cold_start_eligible=False,
        requires_mature=False,
        estimated_impact_band="low",
        conditions={},
        source_note="DEFRA transport swap category — motorbike to bus",
    ),
    RecommendationDefinition(
        id="TRN-005",
        category=Category.TRANSPORT,
        title="Try the Bus Instead of an Auto",
        description_template="Use public transport instead of an auto-rickshaw for this trip.",
        action_type="auto_rickshaw_to_public_transit",
        baseline_activity_key="auto_rickshaw_commute",
        recommended_activity_key="bus_commute",
        default_quantity=6.0,
        unit="km",
        difficulty=Difficulty.EASY,
        tags=("commute", "public_transit", "auto_rickshaw"),
        applicable_pattern_types=("transport_weekday",),
        cold_start_eligible=False,
        requires_mature=False,
        estimated_impact_band="low",
        conditions={},
        source_note="DEFRA transport swap category — auto to bus",
    ),
    RecommendationDefinition(
        id="TRN-006",
        category=Category.TRANSPORT,
        title="Consider an EV for This Route",
        description_template="An electric vehicle would cut emissions on this regular route.",
        action_type="solo_car_to_ev",
        baseline_activity_key="car_solo_commute",
        recommended_activity_key="ev_solo_commute",
        default_quantity=6.0,
        unit="km",
        difficulty=Difficulty.CHALLENGING,
        tags=("commute", "electric_vehicle", "road", "big_ask"),
        applicable_pattern_types=("transport_weekday",),
        cold_start_eligible=False,
        requires_mature=True,
        estimated_impact_band="high",
        conditions={},
        source_note="IEA transport electrification guidance — ICE to EV",
    ),
    RecommendationDefinition(
        id="TRN-007",
        category=Category.TRANSPORT,
        title="Bike This Short Trip",
        description_template="Use a bicycle instead of a car for trips under {count} km.",
        action_type="solo_car_to_bike",
        baseline_activity_key="car_solo_commute",
        recommended_activity_key="bicycle_commute",
        default_quantity=3.0,
        unit="km",
        difficulty=Difficulty.MODERATE,
        tags=("active_transport", "zero_emission", "health"),
        applicable_pattern_types=("transport_weekday", "short_trip"),
        cold_start_eligible=False,
        requires_mature=False,
        estimated_impact_band="medium",
        conditions={"max_distance_km": 5},
        source_note="DEFRA transport swap category — car to cycling",
    ),
    RecommendationDefinition(
        id="TRN-008",
        category=Category.TRANSPORT,
        title="Walk the Last Mile",
        description_template="Park earlier and walk the remaining distance to your destination.",
        action_type="car_to_walk",
        baseline_activity_key="car_solo_commute",
        recommended_activity_key="walk_commute",
        default_quantity=1.0,
        unit="km",
        difficulty=Difficulty.EASY,
        tags=("active_transport", "zero_emission", "health", "micro_mobility"),
        applicable_pattern_types=("transport_weekday", "short_trip"),
        cold_start_eligible=True,
        requires_mature=False,
        estimated_impact_band="low",
        conditions={"max_distance_km": 2},
        source_note="General active transport guidance",
    ),
    RecommendationDefinition(
        id="TRN-009",
        category=Category.TRANSPORT,
        title="Take the Train Instead of Flying",
        description_template="Replace a short-haul flight with a train journey for your next trip.",
        action_type="short_haul_flight_to_train",
        baseline_activity_key="short_haul_flight",
        recommended_activity_key="train_journey",
        default_quantity=300.0,
        unit="km",
        difficulty=Difficulty.MODERATE,
        tags=("aviation", "rail", "long_distance"),
        applicable_pattern_types=("travel_pattern",),
        cold_start_eligible=False,
        requires_mature=False,
        estimated_impact_band="high",
        conditions={"max_distance_km": 800},
        source_note="DEFRA transport swap category — short flight to rail",
    ),
    RecommendationDefinition(
        id="TRN-010",
        category=Category.TRANSPORT,
        title="Replace a Flight with a Video Call",
        description_template="For your next business meeting, consider a video call instead of flying.",
        action_type="long_haul_flight_to_video_call",
        baseline_activity_key="long_haul_flight",
        recommended_activity_key="video_conference",
        default_quantity=1.0,
        unit="trip",
        difficulty=Difficulty.EASY,
        tags=("aviation", "remote_work", "business_travel"),
        applicable_pattern_types=("travel_pattern",),
        cold_start_eligible=True,
        requires_mature=False,
        estimated_impact_band="high",
        conditions={},
        source_note="General remote-work substitution guidance",
    ),
    RecommendationDefinition(
        id="TRN-011",
        category=Category.TRANSPORT,
        title="Upgrade to a Hybrid Vehicle",
        description_template="Consider a hybrid car for your next vehicle purchase.",
        action_type="diesel_car_to_hybrid",
        baseline_activity_key="diesel_car_commute",
        recommended_activity_key="hybrid_car_commute",
        default_quantity=6.0,
        unit="km",
        difficulty=Difficulty.CHALLENGING,
        tags=("vehicle_upgrade", "road", "big_ask"),
        applicable_pattern_types=("transport_weekday",),
        cold_start_eligible=False,
        requires_mature=True,
        estimated_impact_band="medium",
        conditions={},
        source_note="IEA transport electrification guidance — ICE to hybrid",
    ),
    RecommendationDefinition(
        id="TRN-012",
        category=Category.TRANSPORT,
        title="Work From Home Today",
        description_template="Skip the commute and work from home if your schedule allows.",
        action_type="daily_commute_to_work_from_home",
        baseline_activity_key="car_solo_commute",
        recommended_activity_key="telecommute",
        default_quantity=6.0,
        unit="km",
        difficulty=Difficulty.EASY,
        tags=("commute", "remote_work", "zero_emission"),
        applicable_pattern_types=("transport_weekday",),
        cold_start_eligible=False,
        requires_mature=False,
        estimated_impact_band="medium",
        conditions={},
        source_note="General remote-work substitution guidance",
    ),
    RecommendationDefinition(
        id="TRN-013",
        category=Category.TRANSPORT,
        title="Chain Your Errands",
        description_template="Combine multiple short trips into one efficient round trip.",
        action_type="multiple_trips_to_trip_chain",
        baseline_activity_key="multiple_short_trips",
        recommended_activity_key="chained_trip",
        default_quantity=3.0,
        unit="trip",
        difficulty=Difficulty.EASY,
        tags=("trip_efficiency", "planning", "road"),
        applicable_pattern_types=("trip_pattern",),
        cold_start_eligible=True,
        requires_mature=False,
        estimated_impact_band="low",
        conditions={},
        source_note="General transport efficiency guidance",
    ),
    RecommendationDefinition(
        id="TRN-014",
        category=Category.TRANSPORT,
        title="Take the Bus Instead of a Rideshare",
        description_template="Use a public bus rather than a private rideshare for this trip.",
        action_type="rideshare_to_bus",
        baseline_activity_key="rideshare_trip",
        recommended_activity_key="bus_commute",
        default_quantity=6.0,
        unit="km",
        difficulty=Difficulty.EASY,
        tags=("public_transit", "shared_mobility"),
        applicable_pattern_types=("transport_weekday",),
        cold_start_eligible=False,
        requires_mature=False,
        estimated_impact_band="low",
        conditions={},
        source_note="DEFRA transport swap category — rideshare to bus",
    ),
    RecommendationDefinition(
        id="TRN-015",
        category=Category.TRANSPORT,
        title="Switch to a CNG Vehicle",
        description_template="Consider a compressed natural gas vehicle for lower emissions on regular routes.",
        action_type="gas_vehicle_to_cng",
        baseline_activity_key="gasoline_car_commute",
        recommended_activity_key="cng_car_commute",
        default_quantity=6.0,
        unit="km",
        difficulty=Difficulty.CHALLENGING,
        tags=("vehicle_upgrade", "road", "alternative_fuel", "big_ask"),
        applicable_pattern_types=("transport_weekday",),
        cold_start_eligible=False,
        requires_mature=True,
        estimated_impact_band="medium",
        conditions={},
        source_note="IEA alternative fuels guidance",
    ),
    RecommendationDefinition(
        id="TRN-016",
        category=Category.TRANSPORT,
        title="Cross by Bridge Instead of Ferry",
        description_template="Use a bridge or tunnel instead of a ferry for your crossing.",
        action_type="ferry_to_bridge",
        baseline_activity_key="ferry_crossing",
        recommended_activity_key="bridge_crossing",
        default_quantity=5.0,
        unit="km",
        difficulty=Difficulty.EASY,
        tags=("infrastructure", "crossing"),
        applicable_pattern_types=("travel_pattern",),
        cold_start_eligible=False,
        requires_mature=False,
        estimated_impact_band="low",
        conditions={},
        source_note="General transport infrastructure substitution",
    ),
    RecommendationDefinition(
        id="TRN-017",
        category=Category.TRANSPORT,
        title="Turn Off the Engine When Idling",
        description_template="Switch off your engine instead of idling for more than {count} seconds.",
        action_type="idling_to_engine_off",
        baseline_activity_key="engine_idling",
        recommended_activity_key="engine_off",
        default_quantity=60.0,
        unit="second",
        difficulty=Difficulty.EASY,
        tags=("driving_habit", "fuel_efficiency", "road"),
        applicable_pattern_types=("driving_pattern",),
        cold_start_eligible=True,
        requires_mature=False,
        estimated_impact_band="low",
        conditions={},
        source_note="General fuel efficiency guidance",
    ),
    RecommendationDefinition(
        id="TRN-018",
        category=Category.TRANSPORT,
        title="Drive Smoothly",
        description_template="Avoid rapid acceleration and braking to improve fuel efficiency.",
        action_type="aggressive_driving_to_smooth_driving",
        baseline_activity_key="aggressive_driving",
        recommended_activity_key="smooth_driving",
        default_quantity=1.0,
        unit="trip",
        difficulty=Difficulty.EASY,
        tags=("driving_habit", "fuel_efficiency", "road"),
        applicable_pattern_types=("driving_pattern",),
        cold_start_eligible=True,
        requires_mature=False,
        estimated_impact_band="low",
        conditions={},
        source_note="General fuel efficiency guidance",
    ),
]

# ----------------------------------------------------------------------------
# Electricity — 16 entries
# ----------------------------------------------------------------------------

_ELECTRICITY: list[RecommendationDefinition] = [
    RecommendationDefinition(
        id="ELE-001",
        category=Category.ELECTRICITY,
        title="Cut the Standby Drain",
        description_template="Switch off devices instead of leaving them on standby tonight.",
        action_type="standby_to_off",
        baseline_activity_key="standby_power_overnight",
        recommended_activity_key="devices_off_overnight",
        default_quantity=1.0,
        unit="kwh",
        difficulty=Difficulty.EASY,
        tags=("standby", "vampire_power", "home"),
        applicable_pattern_types=("energy_time_of_day",),
        cold_start_eligible=True,
        requires_mature=False,
        estimated_impact_band="low",
        conditions={},
        source_note="DEFRA home energy guidance — standby power reduction",
    ),
    RecommendationDefinition(
        id="ELE-002",
        category=Category.ELECTRICITY,
        title="Switch to LED Bulbs",
        description_template="Replace incandescent bulbs with LEDs in your most-used light fixtures.",
        action_type="incandescent_to_led",
        baseline_activity_key="incandescent_lighting",
        recommended_activity_key="led_lighting",
        default_quantity=3.0,
        unit="bulb",
        difficulty=Difficulty.EASY,
        tags=("lighting", "home", "efficiency"),
        applicable_pattern_types=("energy_time_of_day",),
        cold_start_eligible=True,
        requires_mature=False,
        estimated_impact_band="low",
        conditions={},
        source_note="IEA lighting efficiency guidance",
    ),
    RecommendationDefinition(
        id="ELE-003",
        category=Category.ELECTRICITY,
        title="Upgrade to an Efficient Fridge",
        description_template="Replace an old refrigerator with an energy-efficient model.",
        action_type="old_fridge_to_efficient_fridge",
        baseline_activity_key="old_refrigerator",
        recommended_activity_key="energy_star_refrigerator",
        default_quantity=1.0,
        unit="appliance",
        difficulty=Difficulty.CHALLENGING,
        tags=("appliance_upgrade", "home", "big_ask"),
        applicable_pattern_types=("energy_time_of_day",),
        cold_start_eligible=False,
        requires_mature=True,
        estimated_impact_band="medium",
        conditions={},
        source_note="IEA appliance efficiency guidance",
    ),
    RecommendationDefinition(
        id="ELE-004",
        category=Category.ELECTRICITY,
        title="Install a Heat Pump",
        description_template="Replace an electric resistance heater with a heat pump for space heating.",
        action_type="electric_heater_to_heat_pump",
        baseline_activity_key="electric_resistance_heating",
        recommended_activity_key="heat_pump_heating",
        default_quantity=1.0,
        unit="system",
        difficulty=Difficulty.CHALLENGING,
        tags=("heating", "home", "big_ask", "appliance_upgrade"),
        applicable_pattern_types=("energy_time_of_day",),
        cold_start_eligible=False,
        requires_mature=True,
        estimated_impact_band="high",
        conditions={},
        source_note="IEA heating decarbonisation guidance",
    ),
    RecommendationDefinition(
        id="ELE-005",
        category=Category.ELECTRICITY,
        title="Use a Fan Instead of AC",
        description_template="Try a ceiling fan instead of air conditioning on mild days.",
        action_type="air_conditioner_to_fan",
        baseline_activity_key="air_conditioner_use",
        recommended_activity_key="ceiling_fan_use",
        default_quantity=4.0,
        unit="hour",
        difficulty=Difficulty.EASY,
        tags=("cooling", "home", "efficiency"),
        applicable_pattern_types=("energy_time_of_day",),
        cold_start_eligible=True,
        requires_mature=False,
        estimated_impact_band="low",
        conditions={"max_temperature_c": 28},
        source_note="IEA cooling efficiency guidance",
    ),
    RecommendationDefinition(
        id="ELE-006",
        category=Category.ELECTRICITY,
        title="Air-Dry Your Laundry",
        description_template="Hang clothes to dry instead of using an electric tumble dryer.",
        action_type="dryer_to_clothesline",
        baseline_activity_key="tumble_dryer_use",
        recommended_activity_key="clothesline_drying",
        default_quantity=1.0,
        unit="load",
        difficulty=Difficulty.EASY,
        tags=("laundry", "home", "zero_emission"),
        applicable_pattern_types=("energy_time_of_day",),
        cold_start_eligible=True,
        requires_mature=False,
        estimated_impact_band="medium",
        conditions={},
        source_note="DEFRA home energy guidance — dryer avoidance",
    ),
    RecommendationDefinition(
        id="ELE-007",
        category=Category.ELECTRICITY,
        title="Use a Laptop Instead of Desktop",
        description_template="Work on a laptop rather than a desktop computer for lower power draw.",
        action_type="desktop_to_laptop",
        baseline_activity_key="desktop_computer_use",
        recommended_activity_key="laptop_computer_use",
        default_quantity=4.0,
        unit="hour",
        difficulty=Difficulty.EASY,
        tags=("computing", "home", "office", "efficiency"),
        applicable_pattern_types=("energy_time_of_day",),
        cold_start_eligible=True,
        requires_mature=False,
        estimated_impact_band="low",
        conditions={},
        source_note="General electronics efficiency guidance",
    ),
    RecommendationDefinition(
        id="ELE-008",
        category=Category.ELECTRICITY,
        title="Take Shorter Showers",
        description_template="Limit your shower to under {count} minutes to reduce hot water heating.",
        action_type="long_shower_to_short_shower",
        baseline_activity_key="long_hot_shower",
        recommended_activity_key="short_hot_shower",
        default_quantity=5.0,
        unit="minute",
        difficulty=Difficulty.EASY,
        tags=("water_heating", "home", "hygiene"),
        applicable_pattern_types=("energy_time_of_day",),
        cold_start_eligible=True,
        requires_mature=False,
        estimated_impact_band="low",
        conditions={},
        source_note="DEFRA home energy guidance — hot water reduction",
    ),
    RecommendationDefinition(
        id="ELE-009",
        category=Category.ELECTRICITY,
        title="Cook with Induction",
        description_template="Use an induction cooktop instead of a conventional electric stove.",
        action_type="electric_stove_to_induction",
        baseline_activity_key="electric_resistance_stove",
        recommended_activity_key="induction_cooktop",
        default_quantity=1.0,
        unit="meal",
        difficulty=Difficulty.MODERATE,
        tags=("cooking", "home", "appliance_upgrade"),
        applicable_pattern_types=("energy_time_of_day",),
        cold_start_eligible=False,
        requires_mature=False,
        estimated_impact_band="low",
        conditions={},
        source_note="IEA cooking efficiency guidance",
    ),
    RecommendationDefinition(
        id="ELE-010",
        category=Category.ELECTRICITY,
        title="Install Motion-Sensor Lights",
        description_template="Replace always-on lights with motion-sensor lighting in low-traffic areas.",
        action_type="always_on_lights_to_motion_sensor",
        baseline_activity_key="always_on_lighting",
        recommended_activity_key="motion_sensor_lighting",
        default_quantity=2.0,
        unit="fixture",
        difficulty=Difficulty.MODERATE,
        tags=("lighting", "home", "automation"),
        applicable_pattern_types=("energy_time_of_day",),
        cold_start_eligible=True,
        requires_mature=False,
        estimated_impact_band="low",
        conditions={},
        source_note="General home automation efficiency guidance",
    ),
    RecommendationDefinition(
        id="ELE-011",
        category=Category.ELECTRICITY,
        title="Upgrade to an Inverter AC",
        description_template="Replace an old air conditioner with an inverter-based efficient unit.",
        action_type="old_ac_to_inverter_ac",
        baseline_activity_key="old_air_conditioner",
        recommended_activity_key="inverter_air_conditioner",
        default_quantity=1.0,
        unit="appliance",
        difficulty=Difficulty.CHALLENGING,
        tags=("cooling", "home", "appliance_upgrade", "big_ask"),
        applicable_pattern_types=("energy_time_of_day",),
        cold_start_eligible=False,
        requires_mature=True,
        estimated_impact_band="medium",
        conditions={},
        source_note="IEA cooling efficiency guidance",
    ),
    RecommendationDefinition(
        id="ELE-012",
        category=Category.ELECTRICITY,
        title="Use a Blanket Instead of a Space Heater",
        description_template="Put on warm clothing and use a blanket instead of an electric space heater.",
        action_type="space_heater_to_blanket",
        baseline_activity_key="electric_space_heater",
        recommended_activity_key="blanket_and_layers",
        default_quantity=2.0,
        unit="hour",
        difficulty=Difficulty.EASY,
        tags=("heating", "home", "zero_emission"),
        applicable_pattern_types=("energy_time_of_day",),
        cold_start_eligible=True,
        requires_mature=False,
        estimated_impact_band="low",
        conditions={},
        source_note="General home energy reduction guidance",
    ),
    RecommendationDefinition(
        id="ELE-013",
        category=Category.ELECTRICITY,
        title="Install Solar Water Heating",
        description_template="Replace an electric water heater with a solar thermal system.",
        action_type="electric_water_heater_to_solar",
        baseline_activity_key="electric_water_heater",
        recommended_activity_key="solar_water_heater",
        default_quantity=1.0,
        unit="system",
        difficulty=Difficulty.CHALLENGING,
        tags=("water_heating", "home", "renewable", "big_ask"),
        applicable_pattern_types=("energy_time_of_day",),
        cold_start_eligible=False,
        requires_mature=True,
        estimated_impact_band="high",
        conditions={},
        source_note="IEA renewable heat guidance",
    ),
    RecommendationDefinition(
        id="ELE-014",
        category=Category.ELECTRICITY,
        title="Play Outside Instead of Gaming",
        description_template="Take a break from the console and enjoy an outdoor activity.",
        action_type="gaming_console_to_outdoor_activity",
        baseline_activity_key="gaming_console_use",
        recommended_activity_key="outdoor_recreation",
        default_quantity=2.0,
        unit="hour",
        difficulty=Difficulty.EASY,
        tags=("entertainment", "home", "zero_emission", "health"),
        applicable_pattern_types=("energy_time_of_day",),
        cold_start_eligible=True,
        requires_mature=False,
        estimated_impact_band="low",
        conditions={},
        source_note="General screen-time and energy reduction guidance",
    ),
    RecommendationDefinition(
        id="ELE-015",
        category=Category.ELECTRICITY,
        title="Use One Monitor at a Time",
        description_template="Work with a single monitor instead of multiple displays to reduce power draw.",
        action_type="multiple_monitors_to_single",
        baseline_activity_key="multiple_monitor_setup",
        recommended_activity_key="single_monitor_setup",
        default_quantity=4.0,
        unit="hour",
        difficulty=Difficulty.EASY,
        tags=("computing", "home", "office", "efficiency"),
        applicable_pattern_types=("energy_time_of_day",),
        cold_start_eligible=True,
        requires_mature=False,
        estimated_impact_band="low",
        conditions={},
        source_note="General electronics efficiency guidance",
    ),
    RecommendationDefinition(
        id="ELE-016",
        category=Category.ELECTRICITY,
        title="Upgrade to an Efficient Washing Machine",
        description_template="Replace an old washing machine with an energy-efficient model.",
        action_type="old_washing_machine_to_efficient",
        baseline_activity_key="old_washing_machine",
        recommended_activity_key="energy_star_washing_machine",
        default_quantity=1.0,
        unit="appliance",
        difficulty=Difficulty.CHALLENGING,
        tags=("appliance_upgrade", "home", "laundry", "big_ask"),
        applicable_pattern_types=("energy_time_of_day",),
        cold_start_eligible=False,
        requires_mature=True,
        estimated_impact_band="medium",
        conditions={},
        source_note="IEA appliance efficiency guidance",
    ),
]

# ----------------------------------------------------------------------------
# Water — 8 entries
# ----------------------------------------------------------------------------

_WATER: list[RecommendationDefinition] = [
    RecommendationDefinition(
        id="WAT-001",
        category=Category.WATER,
        title="Take a Five-Minute Shower",
        description_template="Keep your shower under five minutes to save water and the energy used to heat it.",
        action_type="long_shower_to_five_minute",
        baseline_activity_key="long_shower",
        recommended_activity_key="five_minute_shower",
        default_quantity=5.0,
        unit="minute",
        difficulty=Difficulty.EASY,
        tags=("shower", "hot_water", "home"),
        applicable_pattern_types=("water_habit",),
        cold_start_eligible=True,
        requires_mature=False,
        estimated_impact_band="low",
        conditions={},
        source_note="General water conservation guidance",
    ),
    RecommendationDefinition(
        id="WAT-002",
        category=Category.WATER,
        title="Shower Instead of Bathing",
        description_template="Take a short shower instead of filling the bathtub.",
        action_type="bath_to_shower",
        baseline_activity_key="full_bath",
        recommended_activity_key="short_shower",
        default_quantity=1.0,
        unit="bath",
        difficulty=Difficulty.EASY,
        tags=("bath", "shower", "home"),
        applicable_pattern_types=("water_habit",),
        cold_start_eligible=True,
        requires_mature=False,
        estimated_impact_band="low",
        conditions={},
        source_note="General water conservation guidance",
    ),
    RecommendationDefinition(
        id="WAT-003",
        category=Category.WATER,
        title="Use a Bowl Instead of Running Tap",
        description_template="Wash vegetables or dishes in a bowl rather than under a running tap.",
        action_type="running_tap_to_bowl_wash",
        baseline_activity_key="running_tap_wash",
        recommended_activity_key="bowl_wash",
        default_quantity=1.0,
        unit="task",
        difficulty=Difficulty.EASY,
        tags=("kitchen", "home", "tap"),
        applicable_pattern_types=("water_habit",),
        cold_start_eligible=True,
        requires_mature=False,
        estimated_impact_band="low",
        conditions={},
        source_note="General water conservation guidance",
    ),
    RecommendationDefinition(
        id="WAT-004",
        category=Category.WATER,
        title="Use a Bucket for Car Washing",
        description_template="Wash your car with a bucket and sponge instead of a running hose.",
        action_type="hose_to_bucket_car_wash",
        baseline_activity_key="hose_car_wash",
        recommended_activity_key="bucket_car_wash",
        default_quantity=1.0,
        unit="wash",
        difficulty=Difficulty.EASY,
        tags=("outdoor", "vehicle", "home"),
        applicable_pattern_types=("water_habit",),
        cold_start_eligible=True,
        requires_mature=False,
        estimated_impact_band="low",
        conditions={},
        source_note="General water conservation guidance",
    ),
    RecommendationDefinition(
        id="WAT-005",
        category=Category.WATER,
        title="Install Drip Irrigation",
        description_template="Replace lawn sprinklers with drip irrigation for your garden.",
        action_type="lawn_sprinkler_to_drip_irrigation",
        baseline_activity_key="lawn_sprinkler",
        recommended_activity_key="drip_irrigation",
        default_quantity=1.0,
        unit="system",
        difficulty=Difficulty.MODERATE,
        tags=("garden", "outdoor", "home"),
        applicable_pattern_types=("water_habit",),
        cold_start_eligible=False,
        requires_mature=False,
        estimated_impact_band="medium",
        conditions={},
        source_note="General water conservation guidance",
    ),
    RecommendationDefinition(
        id="WAT-006",
        category=Category.WATER,
        title="Install a Dual-Flush Toilet",
        description_template="Upgrade to a dual-flush toilet to reduce water per flush.",
        action_type="single_flush_to_dual_flush",
        baseline_activity_key="single_flush_toilet",
        recommended_activity_key="dual_flush_toilet",
        default_quantity=1.0,
        unit="appliance",
        difficulty=Difficulty.CHALLENGING,
        tags=("bathroom", "home", "appliance_upgrade", "big_ask"),
        applicable_pattern_types=("water_habit",),
        cold_start_eligible=False,
        requires_mature=True,
        estimated_impact_band="low",
        conditions={},
        source_note="General water efficiency guidance",
    ),
    RecommendationDefinition(
        id="WAT-007",
        category=Category.WATER,
        title="Use a Water Filter Instead of Bottled",
        description_template="Drink filtered tap water instead of buying bottled water.",
        action_type="bottled_water_to_filter",
        baseline_activity_key="bottled_water_drinking",
        recommended_activity_key="filtered_tap_water",
        default_quantity=1.0,
        unit="litre",
        difficulty=Difficulty.EASY,
        tags=("drinking", "home", "plastic_reduction"),
        applicable_pattern_types=("water_habit",),
        cold_start_eligible=True,
        requires_mature=False,
        estimated_impact_band="low",
        conditions={},
        source_note="General water and plastic reduction guidance",
    ),
    RecommendationDefinition(
        id="WAT-008",
        category=Category.WATER,
        title="Run Full Laundry Loads",
        description_template="Wait until you have a full load before running the washing machine.",
        action_type="daily_laundry_to_full_load",
        baseline_activity_key="partial_wash_load",
        recommended_activity_key="full_wash_load",
        default_quantity=1.0,
        unit="load",
        difficulty=Difficulty.EASY,
        tags=("laundry", "home", "efficiency"),
        applicable_pattern_types=("water_habit",),
        cold_start_eligible=True,
        requires_mature=False,
        estimated_impact_band="low",
        conditions={},
        source_note="General water and energy efficiency guidance",
    ),
]

# ----------------------------------------------------------------------------
# Shopping — 14 entries
# ----------------------------------------------------------------------------

_SHOPPING: list[RecommendationDefinition] = [
    RecommendationDefinition(
        id="SHP-001",
        category=Category.SHOPPING,
        title="Buy Secondhand Clothing",
        description_template="Choose pre-owned or thrifted clothing instead of buying new fast fashion.",
        action_type="fast_fashion_to_secondhand",
        baseline_activity_key="new_fast_fashion_purchase",
        recommended_activity_key="secondhand_clothing_purchase",
        default_quantity=1.0,
        unit="item",
        difficulty=Difficulty.EASY,
        tags=("clothing", "circular_economy", "zero_waste"),
        applicable_pattern_types=("shopping_habit",),
        cold_start_eligible=True,
        requires_mature=False,
        estimated_impact_band="medium",
        conditions={},
        source_note="General circular economy guidance",
    ),
    RecommendationDefinition(
        id="SHP-002",
        category=Category.SHOPPING,
        title="Buy Refurbished Electronics",
        description_template="Choose a refurbished phone or laptop instead of a brand-new device.",
        action_type="new_electronics_to_refurbished",
        baseline_activity_key="new_electronics_purchase",
        recommended_activity_key="refurbished_electronics_purchase",
        default_quantity=1.0,
        unit="device",
        difficulty=Difficulty.MODERATE,
        tags=("electronics", "circular_economy", "zero_waste"),
        applicable_pattern_types=("shopping_habit",),
        cold_start_eligible=True,
        requires_mature=False,
        estimated_impact_band="medium",
        conditions={},
        source_note="General circular economy guidance",
    ),
    RecommendationDefinition(
        id="SHP-003",
        category=Category.SHOPPING,
        title="Bring Reusable Bags",
        description_template="Use your own reusable bags instead of accepting plastic bags at checkout.",
        action_type="plastic_bags_to_reusable",
        baseline_activity_key="plastic_bag_accepted",
        recommended_activity_key="reusable_bag_used",
        default_quantity=3.0,
        unit="bag",
        difficulty=Difficulty.EASY,
        tags=("plastic_reduction", "zero_waste", "grocery"),
        applicable_pattern_types=("shopping_habit",),
        cold_start_eligible=True,
        requires_mature=False,
        estimated_impact_band="low",
        conditions={},
        source_note="General plastic reduction guidance",
    ),
    RecommendationDefinition(
        id="SHP-004",
        category=Category.SHOPPING,
        title="Use Reusable Containers",
        description_template="Buy food in reusable or refillable containers instead of single-use packaging.",
        action_type="disposable_to_reusable_containers",
        baseline_activity_key="single_use_packaged_goods",
        recommended_activity_key="reusable_container_goods",
        default_quantity=1.0,
        unit="item",
        difficulty=Difficulty.EASY,
        tags=("packaging", "zero_waste", "grocery"),
        applicable_pattern_types=("shopping_habit",),
        cold_start_eligible=True,
        requires_mature=False,
        estimated_impact_band="low",
        conditions={},
        source_note="General zero-waste shopping guidance",
    ),
    RecommendationDefinition(
        id="SHP-005",
        category=Category.SHOPPING,
        title="Buy Local Products",
        description_template="Choose locally produced goods to reduce transport emissions.",
        action_type="imported_goods_to_local",
        baseline_activity_key="imported_goods_purchase",
        recommended_activity_key="local_goods_purchase",
        default_quantity=1.0,
        unit="item",
        difficulty=Difficulty.EASY,
        tags=("local", "food_miles", "grocery"),
        applicable_pattern_types=("shopping_habit",),
        cold_start_eligible=True,
        requires_mature=False,
        estimated_impact_band="low",
        conditions={},
        source_note="General local sourcing guidance",
    ),
    RecommendationDefinition(
        id="SHP-006",
        category=Category.SHOPPING,
        title="Shop in Bulk",
        description_template="Buy staples in bulk to reduce packaging waste per unit.",
        action_type="excessive_packaging_to_bulk",
        baseline_activity_key="individually_packaged_goods",
        recommended_activity_key="bulk_goods_purchase",
        default_quantity=1.0,
        unit="kg",
        difficulty=Difficulty.EASY,
        tags=("packaging", "zero_waste", "grocery"),
        applicable_pattern_types=("shopping_habit",),
        cold_start_eligible=True,
        requires_mature=False,
        estimated_impact_band="low",
        conditions={},
        source_note="General zero-waste shopping guidance",
    ),
    RecommendationDefinition(
        id="SHP-007",
        category=Category.SHOPPING,
        title="Choose Natural Fabrics",
        description_template="Buy clothing made from cotton, linen, or wool instead of synthetic polyester.",
        action_type="synthetic_fabric_to_natural",
        baseline_activity_key="synthetic_fabric_purchase",
        recommended_activity_key="natural_fabric_purchase",
        default_quantity=1.0,
        unit="item",
        difficulty=Difficulty.EASY,
        tags=("clothing", "microplastics", "natural_materials"),
        applicable_pattern_types=("shopping_habit",),
        cold_start_eligible=True,
        requires_mature=False,
        estimated_impact_band="low",
        conditions={},
        source_note="General sustainable fashion guidance",
    ),
    RecommendationDefinition(
        id="SHP-008",
        category=Category.SHOPPING,
        title="Upcycle Old Furniture",
        description_template="Repurpose or refurbish existing furniture instead of buying new.",
        action_type="new_furniture_to_upcycled",
        baseline_activity_key="new_furniture_purchase",
        recommended_activity_key="upcycled_furniture",
        default_quantity=1.0,
        unit="item",
        difficulty=Difficulty.MODERATE,
        tags=("furniture", "circular_economy", "diy"),
        applicable_pattern_types=("shopping_habit",),
        cold_start_eligible=True,
        requires_mature=False,
        estimated_impact_band="medium",
        conditions={},
        source_note="General circular economy guidance",
    ),
    RecommendationDefinition(
        id="SHP-009",
        category=Category.SHOPPING,
        title="Choose E-Books Over Paper",
        description_template="Buy the digital version of your next book instead of a printed copy.",
        action_type="physical_books_to_ebook",
        baseline_activity_key="printed_book_purchase",
        recommended_activity_key="ebook_purchase",
        default_quantity=1.0,
        unit="book",
        difficulty=Difficulty.EASY,
        tags=("reading", "digital", "paper_reduction"),
        applicable_pattern_types=("shopping_habit",),
        cold_start_eligible=True,
        requires_mature=False,
        estimated_impact_band="low",
        conditions={},
        source_note="General paper reduction guidance",
    ),
    RecommendationDefinition(
        id="SHP-010",
        category=Category.SHOPPING,
        title="Wait Before You Buy",
        description_template="Add items to a wishlist and wait {count} days before purchasing to avoid impulse buys.",
        action_type="impulse_buy_to_wait_list",
        baseline_activity_key="impulse_purchase",
        recommended_activity_key="planned_purchase",
        default_quantity=7.0,
        unit="day",
        difficulty=Difficulty.EASY,
        tags=("mindful_consumption", "planning", "retail"),
        applicable_pattern_types=("shopping_habit",),
        cold_start_eligible=True,
        requires_mature=False,
        estimated_impact_band="low",
        conditions={},
        source_note="General anti-consumption guidance",
    ),
    RecommendationDefinition(
        id="SHP-011",
        category=Category.SHOPPING,
        title="Buy Secondhand Toys",
        description_template="Choose pre-owned toys or games for children instead of new ones.",
        action_type="new_toys_to_secondhand",
        baseline_activity_key="new_toy_purchase",
        recommended_activity_key="secondhand_toy_purchase",
        default_quantity=1.0,
        unit="item",
        difficulty=Difficulty.EASY,
        tags=("toys", "circular_economy", "children"),
        applicable_pattern_types=("shopping_habit",),
        cold_start_eligible=True,
        requires_mature=False,
        estimated_impact_band="low",
        conditions={},
        source_note="General circular economy guidance",
    ),
    RecommendationDefinition(
        id="SHP-012",
        category=Category.SHOPPING,
        title="Switch to a Safety Razor",
        description_template="Use a reusable safety razor instead of disposable plastic razors.",
        action_type="disposable_razor_to_safety",
        baseline_activity_key="disposable_razor_purchase",
        recommended_activity_key="safety_razor_use",
        default_quantity=1.0,
        unit="item",
        difficulty=Difficulty.MODERATE,
        tags=("personal_care", "plastic_reduction", "zero_waste"),
        applicable_pattern_types=("shopping_habit",),
        cold_start_eligible=True,
        requires_mature=False,
        estimated_impact_band="low",
        conditions={},
        source_note="General zero-waste personal care guidance",
    ),
    RecommendationDefinition(
        id="SHP-013",
        category=Category.SHOPPING,
        title="Use Cloth Instead of Paper Towels",
        description_template="Replace paper towels with washable cloths for cleaning and drying.",
        action_type="paper_towels_to_cloth",
        baseline_activity_key="paper_towel_use",
        recommended_activity_key="reusable_cloth_use",
        default_quantity=3.0,
        unit="sheet",
        difficulty=Difficulty.EASY,
        tags=("cleaning", "paper_reduction", "zero_waste"),
        applicable_pattern_types=("shopping_habit",),
        cold_start_eligible=True,
        requires_mature=False,
        estimated_impact_band="low",
        conditions={},
        source_note="General zero-waste home guidance",
    ),
    RecommendationDefinition(
        id="SHP-014",
        category=Category.SHOPPING,
        title="Choose Vintage Jewelry",
        description_template="Buy vintage or secondhand jewelry instead of newly mined pieces.",
        action_type="new_jewelry_to_vintage",
        baseline_activity_key="new_jewelry_purchase",
        recommended_activity_key="vintage_jewelry_purchase",
        default_quantity=1.0,
        unit="item",
        difficulty=Difficulty.EASY,
        tags=("jewelry", "circular_economy", "mining_reduction"),
        applicable_pattern_types=("shopping_habit",),
        cold_start_eligible=True,
        requires_mature=False,
        estimated_impact_band="low",
        conditions={},
        source_note="General circular economy guidance",
    ),
]

# ----------------------------------------------------------------------------
# Waste — 14 entries
# ----------------------------------------------------------------------------

_WASTE: list[RecommendationDefinition] = [
    RecommendationDefinition(
        id="WST-001",
        category=Category.WASTE,
        title="Carry a Reusable Bottle",
        description_template="Swap single-use plastic bottles for a reusable one today.",
        action_type="single_use_to_reusable_bottle",
        baseline_activity_key="single_use_plastic_bottle",
        recommended_activity_key="reusable_bottle_use",
        default_quantity=1.0,
        unit="item",
        difficulty=Difficulty.EASY,
        tags=("plastic_reduction", "hydration", "zero_waste"),
        applicable_pattern_types=(),
        cold_start_eligible=True,
        requires_mature=False,
        estimated_impact_band="low",
        conditions={},
        source_note="DEFRA waste reduction guidance — single-use plastics",
    ),
    RecommendationDefinition(
        id="WST-002",
        category=Category.WASTE,
        title="Bring Your Own Cup",
        description_template="Use a reusable cup for your coffee instead of a disposable one.",
        action_type="disposable_cups_to_reusable",
        baseline_activity_key="disposable_coffee_cup",
        recommended_activity_key="reusable_coffee_cup",
        default_quantity=1.0,
        unit="cup",
        difficulty=Difficulty.EASY,
        tags=("coffee", "plastic_reduction", "zero_waste"),
        applicable_pattern_types=("beverage_habit",),
        cold_start_eligible=True,
        requires_mature=False,
        estimated_impact_band="low",
        conditions={},
        source_note="General single-use reduction guidance",
    ),
    RecommendationDefinition(
        id="WST-003",
        category=Category.WASTE,
        title="Use Metal Cutlery",
        description_template="Carry a metal spork or cutlery set instead of using plastic disposables.",
        action_type="plastic_cutlery_to_metal",
        baseline_activity_key="disposable_plastic_cutlery",
        recommended_activity_key="reusable_metal_cutlery",
        default_quantity=1.0,
        unit="set",
        difficulty=Difficulty.EASY,
        tags=("plastic_reduction", "zero_waste", "dining"),
        applicable_pattern_types=("dining_habit",),
        cold_start_eligible=True,
        requires_mature=False,
        estimated_impact_band="low",
        conditions={},
        source_note="General single-use reduction guidance",
    ),
    RecommendationDefinition(
        id="WST-004",
        category=Category.WASTE,
        title="Switch to Cloth Napkins",
        description_template="Use washable cloth napkins instead of disposable paper ones.",
        action_type="paper_napkins_to_cloth",
        baseline_activity_key="disposable_paper_napkin",
        recommended_activity_key="reusable_cloth_napkin",
        default_quantity=1.0,
        unit="napkin",
        difficulty=Difficulty.EASY,
        tags=("paper_reduction", "zero_waste", "dining"),
        applicable_pattern_types=("dining_habit",),
        cold_start_eligible=True,
        requires_mature=False,
        estimated_impact_band="low",
        conditions={},
        source_note="General single-use reduction guidance",
    ),
    RecommendationDefinition(
        id="WST-005",
        category=Category.WASTE,
        title="Start Composting Food Scraps",
        description_template="Collect fruit and vegetable scraps for composting instead of throwing them away.",
        action_type="food_waste_to_compost",
        baseline_activity_key="food_scraps_landfill",
        recommended_activity_key="home_composting",
        default_quantity=1.0,
        unit="kg",
        difficulty=Difficulty.MODERATE,
        tags=("organic_waste", "composting", "zero_waste"),
        applicable_pattern_types=("waste_pattern",),
        cold_start_eligible=True,
        requires_mature=False,
        estimated_impact_band="medium",
        conditions={},
        source_note="WRAP food waste reduction guidance",
    ),
    RecommendationDefinition(
        id="WST-006",
        category=Category.WASTE,
        title="Recycle Properly",
        description_template="Sort recyclable materials instead of sending them to landfill.",
        action_type="landfill_recyclables_to_recycling",
        baseline_activity_key="mixed_waste_landfill",
        recommended_activity_key="sorted_recycling",
        default_quantity=1.0,
        unit="kg",
        difficulty=Difficulty.EASY,
        tags=("recycling", "circular_economy", "zero_waste"),
        applicable_pattern_types=("waste_pattern",),
        cold_start_eligible=True,
        requires_mature=False,
        estimated_impact_band="low",
        conditions={},
        source_note="General recycling guidance",
    ),
    RecommendationDefinition(
        id="WST-007",
        category=Category.WASTE,
        title="Switch to Rechargeable Batteries",
        description_template="Use rechargeable batteries instead of disposable alkaline ones.",
        action_type="disposable_batteries_to_rechargeable",
        baseline_activity_key="disposable_battery_use",
        recommended_activity_key="rechargeable_battery_use",
        default_quantity=4.0,
        unit="battery",
        difficulty=Difficulty.EASY,
        tags=("electronics", "circular_economy", "hazardous_waste"),
        applicable_pattern_types=("shopping_habit",),
        cold_start_eligible=True,
        requires_mature=False,
        estimated_impact_band="low",
        conditions={},
        source_note="General hazardous waste reduction guidance",
    ),
    RecommendationDefinition(
        id="WST-008",
        category=Category.WASTE,
        title="Go Paperless",
        description_template="Switch to digital statements and bills to reduce paper mail.",
        action_type="junk_mail_to_digital",
        baseline_activity_key="paper_mail_received",
        recommended_activity_key="digital_communication",
        default_quantity=1.0,
        unit="letter",
        difficulty=Difficulty.EASY,
        tags=("paper_reduction", "digital", "office"),
        applicable_pattern_types=("mail_habit",),
        cold_start_eligible=True,
        requires_mature=False,
        estimated_impact_band="low",
        conditions={},
        source_note="General paper reduction guidance",
    ),
    RecommendationDefinition(
        id="WST-009",
        category=Category.WASTE,
        title="Try Cloth Diapers",
        description_template="Use cloth diapers instead of disposables for your baby.",
        action_type="disposable_diapers_to_cloth",
        baseline_activity_key="disposable_diaper_use",
        recommended_activity_key="cloth_diaper_use",
        default_quantity=5.0,
        unit="diaper",
        difficulty=Difficulty.MODERATE,
        tags=("baby_care", "zero_waste", "laundry"),
        applicable_pattern_types=("shopping_habit",),
        cold_start_eligible=True,
        requires_mature=False,
        estimated_impact_band="medium",
        conditions={},
        source_note="General zero-waste baby care guidance",
    ),
    RecommendationDefinition(
        id="WST-010",
        category=Category.WASTE,
        title="Wrap with Beeswax",
        description_template="Use beeswax wraps instead of plastic cling film for food storage.",
        action_type="plastic_wrap_to_beeswax",
        baseline_activity_key="plastic_cling_film_use",
        recommended_activity_key="beeswax_wrap_use",
        default_quantity=1.0,
        unit="sheet",
        difficulty=Difficulty.EASY,
        tags=("food_storage", "plastic_reduction", "zero_waste"),
        applicable_pattern_types=("kitchen_habit",),
        cold_start_eligible=True,
        requires_mature=False,
        estimated_impact_band="low",
        conditions={},
        source_note="General zero-waste kitchen guidance",
    ),
    RecommendationDefinition(
        id="WST-011",
        category=Category.WASTE,
        title="Use a Reusable Razor",
        description_template="Switch to a long-lasting safety razor instead of disposable plastic razors.",
        action_type="single_use_razors_to_reusable",
        baseline_activity_key="disposable_razor_use",
        recommended_activity_key="reusable_razor_use",
        default_quantity=1.0,
        unit="razor",
        difficulty=Difficulty.MODERATE,
        tags=("personal_care", "plastic_reduction", "zero_waste"),
        applicable_pattern_types=("shopping_habit",),
        cold_start_eligible=True,
        requires_mature=False,
        estimated_impact_band="low",
        conditions={},
        source_note="General zero-waste personal care guidance",
    ),
    RecommendationDefinition(
        id="WST-012",
        category=Category.WASTE,
        title="Use Washcloths Not Wipes",
        description_template="Clean with a washable cloth instead of disposable wet wipes.",
        action_type="disposable_wipes_to_washcloth",
        baseline_activity_key="disposable_wet_wipe_use",
        recommended_activity_key="reusable_washcloth_use",
        default_quantity=3.0,
        unit="wipe",
        difficulty=Difficulty.EASY,
        tags=("personal_care", "plastic_reduction", "zero_waste"),
        applicable_pattern_types=("hygiene_habit",),
        cold_start_eligible=True,
        requires_mature=False,
        estimated_impact_band="low",
        conditions={},
        source_note="General zero-waste personal care guidance",
    ),
    RecommendationDefinition(
        id="WST-013",
        category=Category.WASTE,
        title="Avoid Styrofoam Containers",
        description_template="Bring your own container for takeout instead of accepting styrofoam.",
        action_type="styrofoam_to_reusable_container",
        baseline_activity_key="styrofoam_takeout_container",
        recommended_activity_key="reusable_takeout_container",
        default_quantity=1.0,
        unit="container",
        difficulty=Difficulty.EASY,
        tags=("food_service", "plastic_reduction", "zero_waste"),
        applicable_pattern_types=("dining_habit",),
        cold_start_eligible=True,
        requires_mature=False,
        estimated_impact_band="low",
        conditions={},
        source_note="General zero-waste dining guidance",
    ),
    RecommendationDefinition(
        id="WST-014",
        category=Category.WASTE,
        title="Skip the Straw",
        description_template="Use a metal or bamboo straw, or go without, instead of a plastic straw.",
        action_type="plastic_straws_to_metal",
        baseline_activity_key="plastic_straw_use",
        recommended_activity_key="reusable_straw_or_none",
        default_quantity=1.0,
        unit="straw",
        difficulty=Difficulty.EASY,
        tags=("plastic_reduction", "zero_waste", "dining"),
        applicable_pattern_types=("dining_habit",),
        cold_start_eligible=True,
        requires_mature=False,
        estimated_impact_band="low",
        conditions={},
        source_note="General single-use plastic reduction guidance",
    ),
]

# ----------------------------------------------------------------------------
# Lifestyle — 16 entries
# ----------------------------------------------------------------------------

_LIFESTYLE: list[RecommendationDefinition] = [
    RecommendationDefinition(
        id="LIF-001",
        category=Category.LIFESTYLE,
        title="Vacation Locally",
        description_template="Explore destinations within {count} km by train or car instead of flying.",
        action_type="long_flight_to_local_vacation",
        baseline_activity_key="long_haul_flight_leisure",
        recommended_activity_key="local_train_travel",
        default_quantity=200.0,
        unit="km",
        difficulty=Difficulty.MODERATE,
        tags=("travel", "staycation", "aviation_reduction"),
        applicable_pattern_types=("travel_pattern",),
        cold_start_eligible=False,
        requires_mature=False,
        estimated_impact_band="high",
        conditions={},
        source_note="General aviation reduction guidance",
    ),
    RecommendationDefinition(
        id="LIF-002",
        category=Category.LIFESTYLE,
        title="Stay at an Eco-Lodge",
        description_template="Choose a certified eco-lodge or green hotel for your next trip.",
        action_type="hotel_to_eco_lodge",
        baseline_activity_key="standard_hotel_stay",
        recommended_activity_key="eco_certified_lodge",
        default_quantity=1.0,
        unit="night",
        difficulty=Difficulty.EASY,
        tags=("travel", "accommodation", "sustainable_tourism"),
        applicable_pattern_types=("travel_pattern",),
        cold_start_eligible=True,
        requires_mature=False,
        estimated_impact_band="low",
        conditions={},
        source_note="General sustainable tourism guidance",
    ),
    RecommendationDefinition(
        id="LIF-003",
        category=Category.LIFESTYLE,
        title="Go Digital with Documents",
        description_template="Use digital documents and e-signatures instead of printing and mailing.",
        action_type="printed_documents_to_digital",
        baseline_activity_key="paper_document_printed",
        recommended_activity_key="digital_document",
        default_quantity=5.0,
        unit="page",
        difficulty=Difficulty.EASY,
        tags=("paper_reduction", "digital", "office"),
        applicable_pattern_types=("work_habit",),
        cold_start_eligible=True,
        requires_mature=False,
        estimated_impact_band="low",
        conditions={},
        source_note="General paper reduction guidance",
    ),
    RecommendationDefinition(
        id="LIF-004",
        category=Category.LIFESTYLE,
        title="Run Outdoors",
        description_template="Go for an outdoor run or walk instead of using a gym treadmill.",
        action_type="gym_treadmill_to_outdoor_run",
        baseline_activity_key="treadmill_exercise",
        recommended_activity_key="outdoor_running",
        default_quantity=0.5,
        unit="hour",
        difficulty=Difficulty.EASY,
        tags=("fitness", "zero_emission", "health", "outdoor"),
        applicable_pattern_types=("exercise_habit",),
        cold_start_eligible=True,
        requires_mature=False,
        estimated_impact_band="low",
        conditions={},
        source_note="General gym energy reduction guidance",
    ),
    RecommendationDefinition(
        id="LIF-005",
        category=Category.LIFESTYLE,
        title="Try a Coworking Space",
        description_template="Work from a shared coworking space instead of heating or cooling your home office alone.",
        action_type="home_office_to_coworking",
        baseline_activity_key="home_office_energy_use",
        recommended_activity_key="coworking_space_use",
        default_quantity=1.0,
        unit="day",
        difficulty=Difficulty.EASY,
        tags=("work", "energy_efficiency", "shared_space"),
        applicable_pattern_types=("work_habit",),
        cold_start_eligible=True,
        requires_mature=False,
        estimated_impact_band="low",
        conditions={},
        source_note="General shared workspace efficiency guidance",
    ),
    RecommendationDefinition(
        id="LIF-006",
        category=Category.LIFESTYLE,
        title="Try a Flexitarian Diet",
        description_template="Aim for {count} meat-free days per week to reduce your food footprint.",
        action_type="meat_centered_diet_to_flexitarian",
        baseline_activity_key="daily_meat_consumption",
        recommended_activity_key="flexitarian_diet",
        default_quantity=2.0,
        unit="day_per_week",
        difficulty=Difficulty.MODERATE,
        tags=("diet", "plant_based", "health"),
        applicable_pattern_types=("meal_pattern",),
        cold_start_eligible=True,
        requires_mature=False,
        estimated_impact_band="high",
        conditions={},
        source_note="Poore & Nemecek 2018 — meat reduction diets",
    ),
    RecommendationDefinition(
        id="LIF-007",
        category=Category.LIFESTYLE,
        title="Repair Before Replacing",
        description_template="Fix your {alternative} instead of buying a new one.",
        action_type="frequent_upgrades_to_repair",
        baseline_activity_key="replace_broken_item",
        recommended_activity_key="repair_item",
        default_quantity=1.0,
        unit="item",
        difficulty=Difficulty.MODERATE,
        tags=("circular_economy", "repair", "zero_waste"),
        applicable_pattern_types=("shopping_habit",),
        cold_start_eligible=True,
        requires_mature=False,
        estimated_impact_band="medium",
        conditions={},
        source_note="General circular economy guidance",
    ),
    RecommendationDefinition(
        id="LIF-008",
        category=Category.LIFESTYLE,
        title="Join a Community Event",
        description_template="Attend a local community gathering instead of a resource-intensive solo activity.",
        action_type="solo_hobbies_to_community_events",
        baseline_activity_key="solo_resource_intensive_hobby",
        recommended_activity_key="community_event_attendance",
        default_quantity=1.0,
        unit="event",
        difficulty=Difficulty.EASY,
        tags=("social", "community", "zero_waste"),
        applicable_pattern_types=("leisure_pattern",),
        cold_start_eligible=True,
        requires_mature=False,
        estimated_impact_band="low",
        conditions={},
        source_note="General community-based sustainability guidance",
    ),
    RecommendationDefinition(
        id="LIF-009",
        category=Category.LIFESTYLE,
        title="Cycle for Fun and Fitness",
        description_template="Go for a recreational bike ride instead of a drive to a leisure destination.",
        action_type="driving_to_cycling",
        baseline_activity_key="car_leisure_trip",
        recommended_activity_key="recreational_cycling",
        default_quantity=5.0,
        unit="km",
        difficulty=Difficulty.EASY,
        tags=("active_transport", "health", "zero_emission", "leisure"),
        applicable_pattern_types=("leisure_pattern",),
        cold_start_eligible=True,
        requires_mature=False,
        estimated_impact_band="low",
        conditions={},
        source_note="General active leisure guidance",
    ),
    RecommendationDefinition(
        id="LIF-010",
        category=Category.LIFESTYLE,
        title="Grill with Electricity",
        description_template="Use an electric grill instead of a charcoal or gas barbecue.",
        action_type="gas_grill_to_electric",
        baseline_activity_key="gas_or_charcoal_bbq",
        recommended_activity_key="electric_grill",
        default_quantity=1.0,
        unit="meal",
        difficulty=Difficulty.MODERATE,
        tags=("cooking", "outdoor", "efficiency"),
        applicable_pattern_types=("leisure_pattern",),
        cold_start_eligible=False,
        requires_mature=False,
        estimated_impact_band="low",
        conditions={},
        source_note="General outdoor cooking efficiency guidance",
    ),
    RecommendationDefinition(
        id="LIF-011",
        category=Category.LIFESTYLE,
        title="Celebrate Without Fireworks",
        description_template="Enjoy LED lanterns or light projections instead of fireworks for celebrations.",
        action_type="fireworks_to_lanterns",
        baseline_activity_key="fireworks_display",
        recommended_activity_key="led_lantern_celebration",
        default_quantity=1.0,
        unit="event",
        difficulty=Difficulty.EASY,
        tags=("celebration", "air_quality", "zero_emission"),
        applicable_pattern_types=("event_pattern",),
        cold_start_eligible=True,
        requires_mature=False,
        estimated_impact_band="low",
        conditions={},
        source_note="General air quality and pollution reduction guidance",
    ),
    RecommendationDefinition(
        id="LIF-012",
        category=Category.LIFESTYLE,
        title="Use Bubbles Not Balloons",
        description_template="Decorate with soap bubbles instead of helium balloons for parties.",
        action_type="helium_balloons_to_bubbles",
        baseline_activity_key="helium_balloon_use",
        recommended_activity_key="soap_bubble_decoration",
        default_quantity=10.0,
        unit="balloon",
        difficulty=Difficulty.EASY,
        tags=("celebration", "zero_waste", "decorations"),
        applicable_pattern_types=("event_pattern",),
        cold_start_eligible=True,
        requires_mature=False,
        estimated_impact_band="low",
        conditions={},
        source_note="General celebration waste reduction guidance",
    ),
    RecommendationDefinition(
        id="LIF-013",
        category=Category.LIFESTYLE,
        title="Use Reusable Party Supplies",
        description_template="Choose reusable plates, cups, and decorations for your next party.",
        action_type="disposable_party_supplies_to_reusable",
        baseline_activity_key="disposable_party_supplies",
        recommended_activity_key="reusable_party_supplies",
        default_quantity=1.0,
        unit="party",
        difficulty=Difficulty.EASY,
        tags=("celebration", "zero_waste", "circular_economy"),
        applicable_pattern_types=("event_pattern",),
        cold_start_eligible=True,
        requires_mature=False,
        estimated_impact_band="low",
        conditions={},
        source_note="General celebration waste reduction guidance",
    ),
    RecommendationDefinition(
        id="LIF-014",
        category=Category.LIFESTYLE,
        title="Clean with Natural Products",
        description_template="Use vinegar, baking soda, or natural cleaners instead of chemical sprays.",
        action_type="chemical_cleaners_to_natural",
        baseline_activity_key="chemical_cleaner_use",
        recommended_activity_key="natural_cleaner_use",
        default_quantity=0.50,
        unit="litre",
        difficulty=Difficulty.EASY,
        tags=("cleaning", "home", "health", "zero_waste"),
        applicable_pattern_types=("cleaning_habit",),
        cold_start_eligible=True,
        requires_mature=False,
        estimated_impact_band="low",
        conditions={},
        source_note="General non-toxic home guidance",
    ),
    RecommendationDefinition(
        id="LIF-015",
        category=Category.LIFESTYLE,
        title="Use Essential Oils Not Air Freshener",
        description_template="Diffuse essential oils or open windows instead of using aerosol air fresheners.",
        action_type="air_freshener_to_essential_oil",
        baseline_activity_key="aerosol_air_freshener",
        recommended_activity_key="essential_oil_diffuser",
        default_quantity=1.0,
        unit="use",
        difficulty=Difficulty.EASY,
        tags=("home", "air_quality", "health"),
        applicable_pattern_types=("cleaning_habit",),
        cold_start_eligible=True,
        requires_mature=False,
        estimated_impact_band="low",
        conditions={},
        source_note="General air quality improvement guidance",
    ),
    RecommendationDefinition(
        id="LIF-016",
        category=Category.LIFESTYLE,
        title="Choose Beeswax Candles",
        description_template="Burn beeswax candles instead of paraffin ones for cleaner indoor air.",
        action_type="synthetic_candles_to_beeswax",
        baseline_activity_key="paraffin_candle_burned",
        recommended_activity_key="beeswax_candle_burned",
        default_quantity=1.0,
        unit="candle",
        difficulty=Difficulty.EASY,
        tags=("home", "air_quality", "natural_materials"),
        applicable_pattern_types=("home_ambiance",),
        cold_start_eligible=True,
        requires_mature=False,
        estimated_impact_band="low",
        conditions={},
        source_note="General indoor air quality guidance",
    ),
]

# ----------------------------------------------------------------------------
# Public corpus
# ----------------------------------------------------------------------------

RECOMMENDATIONS: list[RecommendationDefinition] = (
    _FOOD
    + _TRANSPORT
    + _ELECTRICITY
    + _WATER
    + _SHOPPING
    + _WASTE
    + _LIFESTYLE
)
